services:
  frontend:
    build: ./mern/frontend
    ports:
      - "5173:80"
    networks:
      - mern

  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongo
  
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

networks:
  mern:
    driver: bridge